version: '3'
services:
  prom-client:
    image: harbor.yukifans.com/service/ci-sample:1.0.0
    restart: always
    logging:
      options:
        max-size: 100m
    ports:
      - 9300:9300
    healthcheck:
      test: curl -fsS http://localhost:9300/ || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - sample
networks:
  sample:
